# YOLOv11 布匹瑕疵OBB旋转框检测专用模型配置
# 基于yolo11-fabric-defect.yaml改进，专门用于旋转目标检测
# 集成异常检测、纹理感知、自适应FDConv、动态稀疏等创新模块

# 模型参数
nc: 1  # 类别数量（瑕疵）
scales:  # 模型缩放参数 [depth_multiple, width_multiple, max_channels]
  n: [0.33, 0.25, 1024]  # nano
  s: [0.33, 0.50, 1024]  # small  
  m: [0.67, 0.75, 768]   # medium
  l: [1.00, 1.00, 512]   # large
  x: [1.00, 1.25, 512]   # extra-large

# 主干网络架构（Backbone）
backbone:
  # [from, repeats, module, args]
  # from: 输入来源，-1表示上一层
  # repeats: 模块重复次数
  # module: 模块名称
  # args: 模块参数 [out_channels, kernel_size, stride, ...]
  
  # P1/2 - 初始特征提取
  - [-1, 1, Conv, [64, 3, 2]]  # 0 - 640x640 -> 320x320
  - [-1, 1, Conv, [128, 3, 2]]  # 1 - P2/4 - 320x320 -> 160x160
  
  # 纹理感知特征提取（针对布匹纹理）
  - [-1, 1, TextureAwareFeatureExtractor, [128, 256, 2, True, True, True]]  # 2 - 纹理特征
  
  # C2f模块组1 - 浅层特征
  - [-1, 3, C2f, [128, True]]  # 3
  
  # P3/8 - 增强型FDConv下采样
  - [-1, 1, EnhancedFDConv, [256, 256, 3, 2, 1, 1, True, True, 8, True, 4]]  # 4 - 160x160 -> 80x80
  
  # C2f模块组2 - 中层特征
  - [-1, 6, C2f, [256, True]]  # 5
  
  # LEG模块增强（边缘和高斯特征）
  - [-1, 1, LEG_Module, [256, 0]]  # 6 - stage=0使用Scharr边缘检测
  
  # P4/16 - 动态稀疏卷积下采样
  - [-1, 1, DynamicSparseConv, [512, 512, 3, 2, 1, 3]]  # 7 - 80x80 -> 40x40
  
  # C2f模块组3 - 深层特征
  - [-1, 6, C2f, [512, True]]  # 8
  
  # FDConv增强（原始版本，用于深层）
  - [-1, 1, FDConv, [512, 512, 3, 1, 1]]  # 9
  
  # LEG模块增强（高斯特征）
  - [-1, 1, LEG_Module, [512, 1]]  # 10 - stage=1使用高斯
  
  # P5/32 - 最深层下采样
  - [-1, 1, Conv, [1024, 3, 2]]  # 11 - 40x40 -> 20x20
  
  # C2f模块组4 - 最深层特征
  - [-1, 3, C2f, [1024, True]]  # 12
  
  # SPPF - 空间金字塔池化
  - [-1, 1, SPPF, [1024, 5]]  # 13

# 颈部网络架构（Head）- OBB检测头
head:
  
  # 上采样路径（自顶向下）
  - [13, 1, nn.Upsample, [None, 2, "nearest"]]  # 14 - 20x20 -> 40x40
  - [[-1, 10], 1, Concat, [1]]  # 15 - 与P4层连接
  - [-1, 3, C2f, [512]]  # 16 - 融合特征
  
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]  # 17 - 40x40 -> 80x80
  - [[-1, 6], 1, Concat, [1]]  # 18 - 与P3层连接
  - [-1, 3, C2f, [256]]  # 19 - P3/8输出（小目标）
  
  # 下采样路径（自底向上）
  - [19, 1, EnhancedFDConv, [256, 256, 3, 2, 1, 1, True, True, 8, True, 4]]  # 20 - 80x80 -> 40x40
  - [[-1, 16], 1, Concat, [1]]  # 21 - 与P4特征连接
  - [-1, 3, C2f, [512]]  # 22 - P4/16输出（中目标）
  
  - [22, 1, DynamicSparseConv, [512, 512, 3, 2, 1, 3]]  # 23 - 40x40 -> 20x20
  - [[-1, 13], 1, Concat, [1]]  # 24 - 与P5特征连接
  - [-1, 3, C2f, [1024]]  # 25 - P5/32输出（大目标）
  
  # OBB检测头（旋转框）
  - [[19, 22, 25], 1, OBB, [nc, 180]]  # 26 - OBB Detection head
  # OBB参数说明：
  # nc: 类别数
  # 180: 角度数量（180度范围）

# 自定义模块注册（需要确保这些模块已实现）
custom_modules:
  - anomaly_detection.TextureAwareAnomalyModule
  - texture_aware.TextureAwareFeatureExtractor  
  - adaptive_fdconv.EnhancedFDConv
  - dynamic_sparse.DynamicSparseConv
  - feature_pyramid.AdaptiveFPN
  - LEG.LEG_Module
  - FDConv.FDConv

# OBB特定训练超参数
hyperparameters:
  # 优化器设置
  optimizer: AdamW
  lr0: 0.01  # 初始学习率
  lrf: 0.01  # 最终学习率因子
  momentum: 0.937  # SGD动量/Adam beta1
  weight_decay: 0.0005  # 权重衰减
  
  # 损失权重（OBB特定）
  box: 7.5  # 边界框损失权重
  cls: 0.5  # 分类损失权重
  dfl: 1.5  # 分布焦点损失权重
  angle: 1.0  # 角度损失权重（OBB特有）
  anomaly: 2.0  # 异常检测损失权重
  texture: 1.0  # 纹理损失权重
  
  # 数据增强（针对旋转目标优化）
  hsv_h: 0.015  # 色调增强
  hsv_s: 0.5  # 饱和度增强
  hsv_v: 0.4  # 明度增强
  degrees: 30.0  # 旋转角度（OBB可以使用更大角度）
  translate: 0.2  # 平移
  scale: 0.5  # 缩放
  shear: 5.0  # 剪切（适当增加）
  perspective: 0.001  # 透视变换
  flipud: 0.5  # 上下翻转
  fliplr: 0.5  # 左右翻转
  rotate: 0.5  # 额外旋转概率（OBB特有）
  mosaic: 1.0  # mosaic增强
  mixup: 0.2  # mixup增强
  copy_paste: 0.3  # 复制粘贴增强
  
  # 训练设置
  epochs: 300
  patience: 50
  batch_size: 16
  imgsz: 640
  save_period: 10
  cache: False
  device: 0
  workers: 8
  project: runs/obb_fabric
  name: yolo11_fabric_obb
  exist_ok: False
  pretrained: True
  amp: True
  
  # OBB特定设置
  nms_rotated: True  # 使用旋转NMS
  max_det: 300  # 最大检测数
  multi_label: False  # 单标签模式
  overlap_mask: True  # 训练时掩码重叠
  mask_ratio: 4  # 掩码下采样比例
  
  # 知识蒸馏参数（可选）
  distillation:
    enable: False
    teacher_model: yolo11x-obb.pt
    alpha: 0.7
    beta: 0.3
    temperature: 4.0
    feature_weight: 1.0
    texture_weight: 1.5
    angle_weight: 1.0  # 角度蒸馏权重
    use_dynamic_temp: True

# 异常检测配置
anomaly_detection:
  enabled: True
  threshold: 0.5
  bank_size: 2048
  feature_dim: 256
  temperature: 0.07
  update_bank: True
  use_rotation_invariant: True  # 旋转不变特征
  
# 纹理分析配置  
texture_analysis:
  num_patterns: 8  # 纹理模式数量
  num_orientations: 8  # 方向数量（OBB需要更多方向）
  use_frequency: True  # 使用频域分析
  rotation_augment: True  # 旋转增强
  
# 动态稀疏配置
dynamic_sparse:
  enabled: True
  sparsity_ratio: 0.5
  num_paths: 3
  adaptive_groups: True
  rotation_aware: True  # 旋转感知稀疏
  
# OBB推理优化
inference:
  conf_thres: 0.25  # 置信度阈值
  iou_thres: 0.45  # NMS的IoU阈值
  agnostic_nms: False  # 类别无关NMS
  max_det: 300  # 最大检测数
  fp16: True  # 半精度推理
  rotated_nms: True  # 旋转NMS
  merge_rotated: True  # 合并旋转框
  
# 模型导出配置
export:
  format: onnx  # 导出格式
  imgsz: [640, 640]  # 导出图像大小
  batch_size: 1  # 导出批次大小
  device: 0  # 导出设备
  simplify: True  # ONNX简化
  opset: 12  # ONNX opset版本
  dynamic: False  # 动态批次大小
  rotated_bbox: True  # 支持旋转框

# OBB标签格式说明
# 每行格式: class_id x1 y1 x2 y2 x3 y3 x4 y4
# 8个坐标值表示旋转矩形的4个角点
# 坐标值归一化到[0, 1]范围

# 评估指标（OBB特定）
metrics:
  - mAP50  # IoU=0.5的mAP
  - mAP75  # IoU=0.75的mAP
  - mAP50-95  # IoU从0.5到0.95的平均mAP
  - precision  # 精确率
  - recall  # 召回率
  - angle_error  # 平均角度误差
  - anomaly_auc  # 异常检测AUC