# YOLOv11 布匹瑕疵检测专用模型配置
# 集成所有创新模块：异常检测、纹理感知、自适应FDConv、动态稀疏等

# 模型参数
nc: 1  # 类别数量（瑕疵）
scales:  # 模型缩放参数 [depth_multiple, width_multiple, max_channels]
  n: [0.33, 0.25, 1024]  # nano
  s: [0.33, 0.50, 1024]  # small  
  m: [0.67, 0.75, 768]   # medium
  l: [1.00, 1.00, 512]   # large
  x: [1.00, 1.25, 512]   # extra-large

# 主干网络架构
backbone:
  # [from, repeats, module, args]
  # from: 输入来源，-1表示上一层
  # repeats: 模块重复次数
  # module: 模块名称
  # args: 模块参数
  
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  
  # 纹理感知特征提取
  - [-1, 1, TextureAwareFeatureExtractor, [128, 256, 3, True, True, True]]  # 2
  
  # C2f with FDConv enhancement
  - [-1, 3, C2f, [128, True]]  # 3
  - [-1, 1, EnhancedFDConv, [256, 256, 3, 2, 1, 1, True, True, True]]  # 4-P3/8
  - [-1, 6, C2f, [256, True]]  # 5
  
  # 动态稀疏卷积
  - [-1, 1, DynamicSparseConv, [512, 512, 3, 2, 1, 3]]  # 6-P4/16
  - [-1, 6, C2f, [512, True]]  # 7
  
  # LEG模块增强
  - [-1, 1, LEG_Module, [512, 1]]  # 8
  
  - [-1, 1, Conv, [1024, 3, 2]]  # 9-P5/32
  - [-1, 3, C2f, [1024, True]]  # 10
  
  # SPPF with texture enhancement
  - [-1, 1, SPPF, [1024, 5]]  # 11

# 颈部网络架构（特征金字塔）
head:
  # 异常检测分支
  - [-1, 1, TextureAwareAnomalyModule, [1024, 1, 256, True]]  # 12 - 异常检测输出
  
  # 上采样路径
  - [11, 1, nn.Upsample, [None, 2, "nearest"]]  # 13
  - [[-1, 8], 1, Concat, [1]]  # 14 - cat backbone P4
  - [-1, 3, C2f, [512]]  # 15
  
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]  # 16
  - [[-1, 5], 1, Concat, [1]]  # 17 - cat backbone P3
  - [-1, 3, C2f, [256]]  # 18 (P3/8-small)
  
  # 下采样路径
  - [-1, 1, EnhancedFDConv, [256, 256, 3, 2, 1, 1, True, True, True]]  # 19
  - [[-1, 15], 1, Concat, [1]]  # 20 - cat head P4
  - [-1, 3, C2f, [512]]  # 21 (P4/16-medium)
  
  - [-1, 1, DynamicSparseConv, [512, 512, 3, 2, 1, 3]]  # 22
  - [[-1, 11], 1, Concat, [1]]  # 23 - cat head P5
  - [-1, 3, C2f, [1024]]  # 24 (P5/32-large)
  
  # 多尺度特征金字塔
  - [[18, 21, 24], 1, AdaptiveFPN, [[256, 512, 1024], 256, 3]]  # 25
  
  # 检测头
  - [[18, 21, 24], 1, Detect, [nc]]  # 26 - Detection head

# 自定义模块注册
custom_modules:
  - anomaly_detection.TextureAwareAnomalyModule
  - texture_aware.TextureAwareFeatureExtractor  
  - adaptive_fdconv.EnhancedFDConv
  - adaptive_fdconv.MultiScaleAdaptiveFDConv
  - dynamic_sparse.DynamicSparseConv
  - dynamic_sparse.EfficientSparseBlock
  - feature_pyramid.AdaptiveFPN
  - LEG.LEG_Module
  - FDConv.FDConv

# 训练超参数
hyperparameters:
  # 优化器
  optimizer: AdamW
  lr0: 0.01  # 初始学习率
  lrf: 0.01  # 最终学习率因子
  momentum: 0.937  # SGD动量/Adam beta1
  weight_decay: 0.0005  # 权重衰减
  
  # 损失权重
  box: 7.5  # box损失权重
  cls: 0.5  # 分类损失权重
  dfl: 1.5  # 分布焦点损失权重
  anomaly: 2.0  # 异常检测损失权重
  texture: 1.0  # 纹理损失权重
  
  # 数据增强
  hsv_h: 0.015  # 色调增强
  hsv_s: 0.7  # 饱和度增强
  hsv_v: 0.4  # 明度增强
  degrees: 0.0  # 旋转角度
  translate: 0.1  # 平移
  scale: 0.5  # 缩放
  shear: 0.0  # 剪切
  perspective: 0.0  # 透视变换
  flipud: 0.0  # 上下翻转
  fliplr: 0.5  # 左右翻转
  mosaic: 1.0  # mosaic增强
  mixup: 0.2  # mixup增强
  copy_paste: 0.1  # 复制粘贴增强
  
  # 训练设置
  epochs: 300
  patience: 100
  batch_size: 16
  imgsz: 640
  save_period: 10
  cache: False
  device: 0
  workers: 8
  project: runs/fabric_defect
  name: yolo11_fabric
  exist_ok: False
  pretrained: True
  amp: True
  
  # 知识蒸馏参数（可选）
  distillation:
    enable: False
    teacher_model: yolo11x-fabric-defect.pt
    alpha: 0.7
    beta: 0.3
    temperature: 4.0
    feature_weight: 1.0
    texture_weight: 1.5
    use_dynamic_temp: True

# 异常检测配置
anomaly_detection:
  enabled: True
  threshold: 0.5
  bank_size: 2048
  feature_dim: 256
  temperature: 0.07
  update_bank: True
  
# 纹理分析配置  
texture_analysis:
  num_patterns: 8  # 纹理模式数量
  num_orientations: 4  # 方向数量
  use_frequency: True  # 使用频域分析
  
# 动态稀疏配置
dynamic_sparse:
  enabled: True
  sparsity_ratio: 0.5
  num_paths: 3
  adaptive_groups: True
  
# 推理优化
inference:
  conf_thres: 0.25  # 置信度阈值
  iou_thres: 0.45  # NMS的IoU阈值
  max_det: 300  # 最大检测数
  fp16: True  # 半精度推理
  
# 模型导出配置
export:
  format: onnx  # 导出格式 [torchscript, onnx, openvino, engine, coreml, etc.]
  imgsz: [640, 640]  # 导出图像大小
  batch_size: 1  # 导出批次大小
  device: 0  # 导出设备
  simplify: True  # ONNX简化
  opset: 12  # ONNX opset版本
  dynamic: False  # 动态批次大小